# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.FloatField()),
                ('Aid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('Qsid', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.IntegerField()),
                ('QuesDetail', models.TextField()),
                ('Opt1', models.CharField(max_length=100)),
                ('Opt2', models.CharField(max_length=100)),
                ('Opt3', models.CharField(max_length=100)),
                ('Opt4', models.CharField(max_length=100)),
                ('Hint', models.CharField(blank=True, max_length=100)),
                ('Time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('Qname', models.CharField(max_length=100)),
                ('Privacy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserDetail'),
        ),
        migrations.AddField(
            model_name='questions',
            name='Qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz'),
        ),
        migrations.AddField(
            model_name='attend',
            name='Qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz'),
        ),
        migrations.AddField(
            model_name='attend',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserDetail'),
        ),
        migrations.AlterUniqueTogether(
            name='attend',
            unique_together=set([('Uid', 'Aid', 'Qid')]),
        ),
    ]
