# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160811_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Tags',
        ),
    ]
