# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_quiz_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Hint',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
