# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160811_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Uid',
            field=models.IntegerField(),
        ),
    ]
