# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160811_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
