# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160811_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Uid',
            field=models.CharField(max_length=200),
        ),
    ]
